### ISSUE TITLE
How to add a value to CookieStorage

### ISSUE THREAD

**Issue by NotKeCa** [csharp-leaf/Leaf.xNet#10]
I am grabbing a value via GET which then needs to be placed inside the Cookie for the POST. How do I proceed to do this?

**Comment by NotKeCa** [comment]
I've read the Leaf.xNet source code and I saw that I have to use

var x = new CookieStorage();
x.Set("some values here");

However, I'm not sure which method I have to use.

**Comment by grandsilence** [comment]
```

**Comment by grandsilence** [comment]
```csharp
var req = new HttpRequest();
req.Cookies.Set(string name, string value, string domain, string path = "/");
// or
var cookie = new Cookie(string name, string value, string domain, string path);
req.Cookies.Set(cookie);
```

**Comment by NotKeCa** [comment]
Do you have an idea how to read the cookie during a get request too? :)

**Comment by grandsilence** [comment]
just use `req.Cookies.Get` method
