### ISSUE TITLE
Automatically detect proxy type

### ISSUE THREAD

**Issue by AnErrupTion** [csharp-leaf/Leaf.xNet#100]
Is there a way to automatically detect the type (http, socks4 or socks5) of a proxy without specifying it? So far, I've tried to loop through every type and try to parse the proxy, if it fails then continue the loop, if not then it sets the request's proxyclient.
However, this didn't seem to work. Is there another way to do so?

**Comment by abhay991** [comment]
I don't think such thing exists, you will probably have to check for each protocol or give an option for users to select from the given protocol.

**Comment by AnErrupTion** [comment]
I tried checking for each protocol, but it didn't work. I'll give the code straight away, maybe I did a mistake? I want to check for all type of proxies at the same time.

```
ProxyType[] types = { ProxyType.HTTP, ProxyType.Socks4, ProxyType.Socks5 };
foreach (ProxyType type in types)
{
       bool result = ProxyClient.TryParse(type, proxy, out ProxyClient client);
       if (result) {
            req.Proxy = client;
            if (type == types[0]) proxiesType = "http";
            else if (type == types[1]) proxiesType = "socks4";
            else if (type == types[2]) proxiesType = "socks5";
       }
       else continue;
}
if (string.IsNullOrEmpty(proxiesType)) goto retry;
```

I checked my code again and again, and I can't find the mistake...

**Comment by abhay991** [comment]
By check, I mean you have to go and check on some site to see if it's alive. Maybe you can do head requests on google and see status code to judge the proxy.

**Comment by Plot1337** [comment]
Hey An,

As @abhay991 said, such a thing doesn't exist; however, what you can do is send a request to a server using those proxies, and if the proxy connection was valid, then that also means the proxy protocol was valid.

So I'd do something like this:
```csharp
static void TestProxy()
{
    string proxy = "ip:port";

    Console.WriteLine(IsValidProtocol(ProxyType.HTTP, proxy) ? "Valid HTTP proxy" : "Invalid HTTP proxy");
    Console.WriteLine(IsValidProtocol(ProxyType.Socks4A, proxy) ? "Valid Socks-4A proxy" : "Invalid Socks-4A proxy");
    Console.WriteLine(IsValidProtocol(ProxyType.Socks4, proxy) ? "Valid Socks-4 proxy" : "Invalid Socks-4 proxy");
    Console.WriteLine(IsValidProtocol(ProxyType.Socks5, proxy) ? "Valid Socks-5 proxy" : "Invalid Socks-5 proxy");
}

static bool IsValidProtocol(ProxyType proxyType, string proxy)
{
    using (var req = new HttpRequest())
    {
        try
        {
            req.Proxy = ProxyClient.Parse(proxyType, proxy);
            req.Get("https://example.com");
            return true;
        }
        catch { return false; }
    }
}
```

Also, your proxy provider should specify proxy protocol(s) the provided proxies support; and if they didn't, I think it's best if you switch to another proxy provider.
