### ISSUE TITLE
HTTP 2.0

### ISSUE THREAD

**Issue by maloibtc** [csharp-leaf/Leaf.xNet#101]
Привет. Поддерживается ли уже протокол HTTP 2.0?
Если да то как его установить?

**Comment by grandsilence** [comment]
Привет. Поддержки HTTP/2 нет, протокол сильно отличается от 1.1.
Поддержка HTTP 2 под Windows и Linux сейчас условная на всех .NET платформах.
Если у вас есть время и способности его реализовать — открывайте Pull Request.
