### ISSUE TITLE
can't get request stream

### ISSUE THREAD

**Issue by qassem231** [csharp-leaf/Leaf.xNet#102]
i want to make a post request but post the data on specific time (hold the request) , so i want to first make the request and get the request stream and then write the post data . 
so i shouldn't do the post request with one line request.post("","","");
i need to make var request = new httprequest(uri);
{
and then do stuff here
}
the problem is that i can't get request stream , i have searched a lot and did't knew how to get it .

**Comment by DeclanFrampton** [comment]
Can you explain in more detail so I am able to replicate the issue on my side.
