### ISSUE TITLE
proxy authentication

### ISSUE THREAD

**Issue by LuisGraphyFVX** [csharp-leaf/Leaf.xNet#104]
как я могу сделать аутентификацию прокси
У меня есть адрес, порт, пользователь, формат пароля
но я получаю сообщение об ошибке, что мне нужно создать класс

**Comment by Plot1337** [comment]
Hey Luis,

Leaf.xNet automatically parses the username and password from a proxy string. For more context, please take a look at this: [https://github.com/csharp-leaf/Leaf.xNet/blob/master/Leaf.xNet/~Proxy/ProxyClient.cs#L304-L311](https://github.com/csharp-leaf/Leaf.xNet/blob/master/Leaf.xNet/~Proxy/ProxyClient.cs#L304-L311)

So you can do something like this:
```csharp
req.Proxy = Socks5ProxyClient.Parse("address:port:username:password");
```

Hope this helps 😊

**Comment by muratulashozturk** [comment]
Hi, I am using this. Properly works

```cs
string pProxy = "address:port:username:password";
string[] pArray = pProxy.Split(':');
var aProxy = HttpProxyClient.Parse($"{pArray[0]}:{pArray[1]}");
aProxy.Username = pArray[2];
aProxy.Password = pArray[3];
httpRequest.Proxy = aProxy;
```

**Comment by grandsilence** [comment]
Also you can set it via properties:

```csharp
// HTTP/S Proxy
var httpProxy = HttpProxyClient.Parse("127.0.0.1:8888");
httpProxy.Username = "login";
httpProxy.Password = "password";
// Activate proxy for HttpRequest
httpRequest.Proxy = httpProxy;

// SOCKS5
var socks5proxy = Socks5ProxyClient.Parse("127.0.0.1:8888");
socks5proxy.Username = "login";
socks5proxy.Password = "password";
// Activate proxy for HttpRequest
httpRequest.Proxy = socks5proxy;
```
