### ISSUE TITLE
How to set Bearer Token

### ISSUE THREAD

**Issue by muratulashozturk** [csharp-leaf/Leaf.xNet#106]
Hello, I was wondering how to set the Bearer token in my headers. I tried it with 
`httpRequest.AddHeader("authorization", "bearer "+ token);`
But it didn't work. How can I set it?
If it's with `httpRequest.Authorization ` how can I use it?

**Comment by Plot1337** [comment]
Hey Mura,

I think it's an issue on the API's end; maybe it's case sensitive? Try to capitalize, and perhaps then it will work.
```csharp
// Option one:
httpRequest.AddHeader("Authorization", $"Bearer {token}");

// Option two:
httpRequest.Authorization = $"Bearer {token}";

// Option three:
httpRequest["Authorization"] = $"Bearer {token}";
```
"Option three" sets a permanent header, this means all the requests it sends will contain the bearer token. More info: [https://github.com/csharp-leaf/Leaf.xNet/issues/35](https://github.com/csharp-leaf/Leaf.xNet/issues/35)

**Comment by muratulashozturk** [comment]
Yeah you are right! There was an error with my token. I solved it. Thanks.

**Comment by muratulashozturk** [comment]
the error has happened due to duplicate characters in the token.
