### ISSUE TITLE
Proxy Auth

### ISSUE THREAD

**Issue by Ostrich2020** [csharp-leaf/Leaf.xNet#110]
```
var slpt = Proxies.GetProxy(); //returns proxy with proxy type
string[] px = slpt[0].Split(':'); //splits proxy and proxy type
if (slpt[1] == ("1")) //checks proxy type
{
         var aProxy = HttpProxyClient.Parse(px[0] + ":" + px[1]); 
         try
         {
                aProxy.Username = px[2];
                aProxy.Password = px[3];
          }
          catch { }
          httpRequest.Proxy = aProxy;
}
```
This seems to keep giving me unable to connect and I'm not sure why, I've tried `HttpProxyClient.Parse(proxy:port:user:pass)` too but doesn't seem to work either, just returns as unable to connect. I can assure you that the proxy(s) I use are functional.

**Comment by Ostrich2020** [comment]
ok, so I tested `HttpProxyClient.Parse(proxy:port:user:pass)` with another proxy provider and it seemed to work, but with other proxy providers like "Smartproxy" and "Ipvanish", they don't work.

**Comment by muratulashozturk** [comment]
Yeah IPVanish is not working too. I am following thread.

**Comment by abhay991** [comment]
`req.Proxy = new HttpProxyClient("127.0.0.1", 80, "user", "pass");`

Did anyone try this way?

**Comment by muratulashozturk** [comment]
> `req.Proxy = new HttpProxyClient("127.0.0.1", 80, "user", "pass");`
> 
> Did anyone try this way?
Not working

**Comment by Plot1337** [comment]
xNet automatically parses the credentials from the proxy string. Please check this for more info: https://github.com/csharp-leaf/Leaf.xNet/blob/master/Leaf.xNet/~Proxy/ProxyClient.cs#L271-L311

**Comment by muratulashozturk** [comment]
> xNet automatically parses the credentials from the proxy string. Please check this for more info: https://github.com/csharp-leaf/Leaf.xNet/blob/master/Leaf.xNet/~Proxy/ProxyClient.cs#L271-L311

It's not about parsing I guess. In some proxies like ipvanish or limunati IP address is not available. for example server1.domain.com:8000

**Comment by grandsilence** [comment]
Duplicate #104.
