### ISSUE TITLE
DownloadString

### ISSUE THREAD

**Issue by harethpy** [csharp-leaf/Leaf.xNet#114]
I decided to use Leaf.xNet instead of default xNet and WebClient
I setup everything but can't figure out how to DownloadString from website or download the page text

like webclient.DownloadString(addr)

**Comment by Plot1337** [comment]
Hey harethpy,

I assume you mean an HTTP GET request, correct? To do that, simply call `HttpRequest.Get(URL, [REQUEST_PARAMS])`.

Example:
```csharp
var req = new HttpRequest();

var res = req.Get("https://github.com"); // HTTP response from the server
string body = req.ToString(); // Request body

// body: <!doctype html><html lang="en"><head> ...

// You can also do something like this:
string str = req.Get(...).ToString();
```

--
Kind regards, Plot.
