### ISSUE TITLE
Specify HTTP Version

### ISSUE THREAD

**Issue by freeze-out** [csharp-leaf/Leaf.xNet#116]
Hello,

can I specify the HTTP version (1.0, 1.1, etc.) to be used when doing an HTTP request?

Thanks in advance.

**Comment by Plot1337** [comment]
I don't think xNet (or any of its forks) supports this feature yet.

**Comment by grandsilence** [comment]
@freeze-out You should try:

```csharp
// HttpRequest is a static class access (not an instance)
HttpRequest.ProtocolVersion = new Version(1, 1);
```

**Comment by AnimeIsDev** [comment]
@grandsilence maybe update please, I would really appreciate HTTP/2 implementation!
