### ISSUE TITLE
Error 401 JWT Token not found

### ISSUE THREAD

**Issue by tindoescode** [csharp-leaf/Leaf.xNet#119]
Hi,

I am trying to implement api.mail.tm, 

**Here is the code:**

```C#
HttpRequest http = null;
try
{
    http = new HttpRequest();

    http.AddHeader(HttpHeader.Accept, "application/ld+json");

    http.AcceptEncoding = "gzip, deflate, br";
    http.AddHeader(HttpHeader.AcceptLanguage, "accept-language: en-GB,en;q=0.9,vi-VN;q=0.8,vi;q=0.7,en-US;q=0.6");
    http.UseCookies = true;

    var cookieStorage = new CookieStorage();
    cookieStorage.Add(new System.Net.Cookie("__cfduid", "dd951389119c553d06d380070e454e6e71612715886", "/", ".mail.tm"));
    http.Cookies = cookieStorage;
    http.UserAgentRandomize();

    var reqBody = "{\"address\":\"toiyexxxczxxxxxcxuvn@baybabes.com\",\"password\":\"aimabiet\"}";

    http.IgnoreProtocolErrors = true;

    var res = http.Post("https://api.mail.tm/accounts",
        reqBody,
        "application/ld+json");

    var jsonRes = res.ToString();
}
catch(HttpException ex)
{
    Console.WriteLine(ex.Message);
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
finally
{
    http?.Dispose();
}
```

**Error:**
![image](https://user-images.githubusercontent.com/40380704/107183823-0c1b3f80-6a12-11eb-946f-57832be39ebe.png)

**The command they gave me works:**
`curl -X POST "https://api.mail.tm/accounts" -H  "accept: application/ld+json" -H  "Authorization: fzxczx123" -H  "Content-Type: application/ld+json" -d "{\"address\":\"24hsdello1213231f@baybabes.com\",\"password\":\"string\"}"`
![image](https://user-images.githubusercontent.com/40380704/107183630-b6df2e00-6a11-11eb-92ea-321c99a2e582.png)

I have not implement JWT Token before, Bearer token works. How can I make JWT works.

**Comment by sent** [comment]
Hello,

You don't need to provide JWT token when creating account and running same command twice would definitely result in error (See "address: This value is already used.") 

Thanks!
