### ISSUE TITLE
How To Add Cookies in Post Request ?

### ISSUE THREAD

**Issue by HackWithAshwin** [csharp-leaf/Leaf.xNet#125]
Hey there, I did not got how to add cookies in the post req like 

for example we add headers and send post like this: 
req.AddHeader("", "")
req.post("url", "postdata", "type")

so how can i add cookies to this post data?

**Comment by Velka-DEV** [comment]
If it's your first request with the HttpRequest named req, you need to init the Cookie Storage. Like that

`req.Cookies = new CookieStorage()`

After that you can add cookies with `req.Cookies.Add()`
