### ISSUE TITLE
Is it support ShadowSocks proxies?

### ISSUE THREAD

**Issue by SirDeveloperOrg** [csharp-leaf/Leaf.xNet#131]
Hi, sorry for submitting another issue, So all we know that HQ free proxies are really rare, but there is a lot of free HQ ShadowSocks proxies on internet, so is it possible to use them on this Library?
Example: ss://YWVzLTI1Ni1nY206S3F1djVVaHZaWE5NZW1BUXk4RHhaN3Fu@95.57.207.202:38620#Kazakhstan%20%F0%9F%87%B0%F0%9F%87%BF

**Comment by Plot1337** [comment]
Hey SirDeveloper,

This fork of xNet doesn't support "ShadowSocks." The only proxy types that are supported are HTTP(s), Socks4(A), and Socks5.

Can I have more info regarding this proxy type?

**Comment by SirDeveloperOrg** [comment]
[About Shadowsocks on Wikipedia](https://en.wikipedia.org/wiki/Shadowsocks)
[Free Shadowsocks proxy](https://sshocean.com/shadowsocks)

**Comment by SirDeveloperOrg** [comment]
> Hey SirDeveloper,
> 
> This fork of xNet doesn't support "ShadowSocks." The only proxy types that are supported are HTTP(s), Socks4(A), and Socks5.
> 
> Can I have more info regarding this proxy type?

[About Shadowsocks on Wikipedia](https://en.wikipedia.org/wiki/Shadowsocks)
[Free Shadowsocks proxy](https://sshocean.com/shadowsocks)

**Comment by SirDeveloperOrg** [comment]
Its can be useful: [v2rayN](https://github.com/2dust/v2rayN)

**Comment by grandsilence** [comment]
There are no plans to support ShadowSocks. You can open a Pull Request and help the community with this.
