### ISSUE TITLE
how do i post with formdata?

### ISSUE THREAD

**Issue by wulu-epic** [csharp-leaf/Leaf.xNet#133]
what the title says

what ive tried
```
            var urlParams = new RequestParams();
            urlParams["device_type"] = "com.crunchyroll.manga.android";
            urlParams["device_id"] = "996f20f5e235e2b6";
            urlParams["access_token"] = "FLpcfZH4CbW4muO&api_ver=1.0";
            urlParams["account"] = email;
            urlParams["password"] = password;

            var response = httpRequest.Post(url, urlParams);
```

it keeps returning null which means its not getting any form data

**Comment by Plot1337** [comment]
Greetings,

If you mean multipart form data (content-type: `multipart/form-data`), the author mentioned how you can implement this in the readme, https://github.com/csharp-leaf/Leaf.xNet#send-multipart-requests-with-fields-and-files.

However, I assume you are trying to send form URL-encoded data (content-type:  `application/x-www-form-urlencoded`). Unfourtuitnily, this folk of xNet does not have native support of such a thing; thus, you would have to do it manually. Please check the code I provided below.

### Converter:
```csharp
public static string ToFormData(IDictionary<string, object> dict)
{
    var list = new List<string>();

    foreach (var item in dict)
        list.Add(item.Key + "=" + item.Value);

    return string.Join("&", list);
}
```

### Usage:
```csharp
var req = new HttpRequest();

var dict = new Dictionary<string, object>
{
    { "key", "value" },
    { "key_2", 1 },
    { "key_3", false }
};

// NOTE: You NEED to include the content type
req.Post(url, ToFormData(dict), "application/x-www-form-urlencoded");
// key=value&key_2=1&key_3=False
```

Hope this helped!

**Comment by wulu-epic** [comment]
Thanks for the response, it works!
