### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by HideakiAtsuyo** [csharp-leaf/Leaf.xNet#134]
Hello, is there any special difference between ProxyClient & TypeClient (HttpClient, etc..) ?

**Comment by HideakiAtsuyo** [comment]
+ I there is an issue with Socks4 proxy with user authentification =>
![](https://i.imgur.com/eibwxJF.png)

**Comment by abhay991** [comment]
As far as i know Socks4 & 4A do not support username & password authentication. Try using Socks5 for that purpose.

**Comment by HideakiAtsuyo** [comment]
> As far as i know Socks4 & 4A do not support username & password authentication. Try using Socks5 for that purpose.
> 
> https://en.wikipedia.org/wiki/SOCKS

Yeah I see, then the username should be removed from it too ? Since there is no point on using a username without password anyone would be able to use it..

**Comment by abhay991** [comment]
> > As far as i know Socks4 & 4A do not support username & password authentication. Try using Socks5 for that purpose.
> > https://en.wikipedia.org/wiki/SOCKS
> 
> Yeah I see, then the username should be removed from it too ? Since there is no point on using a username without password anyone would be able to use it..

yep that constructor can be removed i guess.

**Comment by HideakiAtsuyo** [comment]
> Hello, is there any special difference between ProxyClient & TypeClient (HttpClient, etc..) ?

If someone can reply to this, it would be enough to close this issue :)
