### ISSUE TITLE
IgnoreProtocolErrors - what is it?

### ISSUE THREAD

**Issue by Devspec** [csharp-leaf/Leaf.xNet#15]
Hi!

I sometimes receive error "The error on the client side. Status code: 404". But in browser it's not 404 - it's absolutely 200! With IgnoreProtocolErrors this exception not raises.
So, IgnoreProtocolErrors - what means this option?

Thanks.

**Comment by grandsilence** [comment]
What leaf version are you using? Send me URL for request
