### ISSUE TITLE
How I Can Read Cookies

### ISSUE THREAD

**Issue by s0ciopa7h** [csharp-leaf/Leaf.xNet#16]
on old xnet lib
Dim GetLink As String = requets.Get("https://twitter.com/login").ToString
TextBox1.Text = requests.Cookies.ToString
and now it's not work with leaf.xnet

**Comment by grandsilence** [comment]
```csharp

**Comment by grandsilence** [comment]
Leaf.xNet using native cookie storage with cross-domain cookies so you need to provide resource url before get cookie collection.
```csharp
var req = new HttpRequest();
string response = req.Get("https://twitter.com/login").ToString();
var cookies = req.Cookies.GetCookies("https://twitter.com");
```

**Comment by s0ciopa7h** [comment]
How to Convert to string ?
![2018-11-07_192153](https://user-images.githubusercontent.com/42713227/48151776-76d4f200-e2c2-11e8-806b-5709a7a7818d.png)
when i try like this (the result in photo)
            var req = new HttpRequest();
            string response = req.Get("https://twitter.com/login").ToString();
            var cookies = req.Cookies.GetCookies("https://twitter.com");
            txtbbb.Text = cookies.ToString();

**Comment by grandsilence** [comment]
```

**Comment by grandsilence** [comment]
```csharp
foreach (Cookie cookie in cookies) {
    // concat your string or do what you want
    Console.WriteLine(cookie.Name + ": " + cookie.Value);
}
```

**Comment by s0ciopa7h** [comment]
Thnx You Sir <3

**Comment by AliAp7** [comment]
Hello Man
I used you way and it worked
but it just shows one of the cookies 
the others will not be able to see

what can i do till i get all the cookies?
thnks
