### ISSUE TITLE
URL Rewrite causes POST request failure

### ISSUE THREAD

**Issue by DrVisi0n** [csharp-leaf/Leaf.xNet#17]
when sending a POST request to a URL and it gets a redirect, either HTTP to HTTPS or WWW. to non WWW. or the reverse.
The request don't follow, and just returns empty response.

**Comment by grandsilence** [comment]
Did you set AutoRedirect for HttpRequrest? Give me a url for tests. Thx

**Comment by DrVisi0n** [comment]
Yes ofc AllowAutoRedirect = true;
Any form on any web page that needs a url redirection can be used for testing.
The request turns to GET afterwards and POST is dropped.

**Comment by grandsilence** [comment]
It is not the library issue. That’s how HTTP servers working, redirects won’t post form again.
