### ISSUE TITLE
Use Leaf.xNet with https proxy

### ISSUE THREAD

**Issue by khang0001** [csharp-leaf/Leaf.xNet#2]
Hi,

I use your lib to connect with https proxy but have error. This is my code

> using (var request = new HttpRequest())
            {
                request.UserAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.2 Safari/537.36";

                request.AddHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
                request.AddHeader("Accept-Language", "en-US,en;q=0.9");

                var socksProxy = new HttpProxyClient("123.123.123.123", 443, "user", "pass");
                request.Proxy = socksProxy;

                Html = request.Get("https://whoer.net/").ToString();
}

Have error is
Unable to connect to the HTTP-server 'whoer.net'.

How can I fix it?

**Comment by grandsilence** [comment]
Check if your proxy works via [ProxyChecker](https://github.com/csharp-leaf/Leaf.xNet/files/2040518/ProxyChecker.zip)

```csharp

**Comment by khang0001** [comment]
Hi my https proxy with port 443 very special. It use with url address not with ip address. When I test with proxy checker it not success because proxy checker use ip address to login. But I use in my own chrome is success very well load any webpage very fast. Can I Pm you info my proxy with user, pass, host, port to test ?

**Comment by grandsilence** [comment]
Sorry. This lib won't support DNS resolving proxies.
