### ISSUE TITLE
Проверка куки без домена

### ISSUE THREAD

**Issue by koxap** [csharp-leaf/Leaf.xNet#23]
Сабж.
Как можно проверить наличие куки в CookieStorage без домена?

В CookieDictionary можно было использовать ContainsKey(""), и все.

Спасибо.

**Comment by grandsilence** [comment]
Никак. Куки всегда привязаны к определенному домену, как и в обычном браузере. Вне домена они существовать не могут по определению. Используется оригинальное хранилище Cookies из .Net. CookieStorage это всего лишь обертка. В чем проблема указать домен? Или вы не знаете куда переходите?))

**Comment by koxap** [comment]
Все ради удоств.)
Порой куки, привязанные к одному домену, используются с другим доменом.
