### ISSUE TITLE
How to find a value in source page?

### ISSUE THREAD

**Issue by Prophesied** [csharp-leaf/Leaf.xNet#25]
Using Leaf.xNet, we can check if the request is a certain content type with Response.ContentType.ToString(), but how do we do this for a value in the source page? 

Thanks.

**Comment by koxap** [comment]
```
```
request.Get("site.com");
string content = request.Response.ToString();
// let suppose that your value will be here
// type="hidden" name="spiderman" value="***your_value***" ...
```

//you need to use this:
// using Leaf.xNet.Extensions
string parsed = StringExtensions.Substring(content, "spiderman\" value=\"", "\"");



```

**Comment by grandsilence** [comment]
```csharp

**Comment by grandsilence** [comment]
```csharp
// Add in the beginning 
using Leaf.xNet.Extensions;

// Add in your method
// Don't forget about Dispose HttpRequest (use using statement or call r.Dispose())
var r = new HttpRequest();
string html = r.Get("https://google.com").ToString();
string title = html.Substring("<title>", "</title>");
```

**Comment by grandsilence** [comment]
> request.Get("site.com");
> string content = request.Response.ToString();
> // let suppose that your value will be here
> // type="hidden" name="spiderman" value="_**your_value**_" ...
> 
> ```
> 
> //you need to use this:
> // using Leaf.xNet.Extensions
> string parsed = StringExtensions.Substring(content, "spiderman\" value=\"", "\"");
> ```

`StringExtensions` is Extension class for all strings. So it can be called like `yourStringVariable.Substring()`.
