### ISSUE TITLE
RequestParams

### ISSUE THREAD

**Issue by sergey-prokhorov** [csharp-leaf/Leaf.xNet#28]
в POST-запросе на сайт нужно передавать несколько параметров с одним именем, но разнами значениями (предполагается конвертирование в массив):
RequestParams["a[]"] = value1;
RequestParams["a[]"] = value2;
RequestParams["a[]"] = value3;
было бы неплохо добавить реализацию в базовый класс

**Comment by grandsilence** [comment]
Это можно сделать и без базовой реализации, через обычный Extension метод:

**Comment by sergey-prokhorov** [comment]
я не о том КАК это сделать, просто подумал, может пригодится :)
