### ISSUE TITLE
Can't get all the cookies

### ISSUE THREAD

**Issue by ThunderCls** [csharp-leaf/Leaf.xNet#3]
Hey, I just got a little issue with cookies retrieving. The thing is, I'm sending a GET request to this url in order to get a list of cookies before sending a further POST request and include these cookies on it. The issue is that I'm being only able to get 2 cookies out of 5. These are all the cookies I'm suppossed to get

![leaf_issue](https://user-images.githubusercontent.com/13303069/40697291-931d4fa2-6397-11e8-991d-995ee2b20ddb.PNG)

But as seen in this other pic I'm only getting 2 out 5

![leaf_issue3](https://user-images.githubusercontent.com/13303069/40697318-ad4b4abe-6397-11e8-8bcd-ac15e6f853b6.PNG)

Notice that I'm cancelling auto-redirections (even tho the original url doesn't have redirs), So far I don't know what else to try. Is this a bug in the lib or this is just me missing something?
Thanks in advance

**Comment by grandsilence** [comment]
Are you using the latest version of Leaf.xNet?
What is URL for GET request?

Please use Charles for debug:
1) Set http proxy for your `httpRequest` via `.Proxy` = "http://127.0.0.1:8888"
2) Check count `Set-Cookie` headers

**Comment by ThunderCls** [comment]
Hey thanks for replying

1- I'm using v4.3.3.2 of the library (I'm afraid some changes on newer versions might break my code so far, or maybe I'm being too paranoid)
2- The url I'm reaching is: https://adfoc.us/
3- The first image showing the response headers cookies comes from debugging my code with HTTP Debugger Pro. The cookies are sent from the server to my app correctly but the lib somehow doesn't get them all.

**Comment by ThunderCls** [comment]
Another test using Charles shows the same behavior, it only takes the first two cookies.

![image](https://user-images.githubusercontent.com/13303069/40750427-4a33c5de-6435-11e8-84d4-3c010b84fc76.png)

**Comment by ThunderCls** [comment]
Ok, I'll keep posting here any other updates.
I think I found the main issue. It's not about the lib itself...I mean, the thing happens in this line:

[Cookies.Set(_request.Address, headerValue);](https://github.com/csharp-leaf/Leaf.xNet/blob/a4d4e7cca275a2418974b49939952e1bca6653f9/Leaf.xNet/~Http/HttpResponse.cs#L908)

These three cookies's "expires" date/time values are the cause of the "issue". Since those dates appears in the past, then the cookies are immediately deleted and so the CookiesContainer won't get updated when leaving that line. I guess that's the expected behavior since you don't want to pass expired cookies to a further request...concluding that, I suppose there's no bug after all.

My question at this point is...could it be to have something like a "RawHeaders" field in HttpRequest/HttpResponse so you could have an untouched replica of every request/response header, including "Set-Cookie" ones so users could have an option to parse directly the values they needed to?

**Comment by grandsilence** [comment]
Sorry I'm not support v4.3.3.2 version. Please use NuGet with actual version.
But there is no issue for both v4 and v5. 
2 Cookies is correct because another 3 are expired (max-age=0 and look at expire date).
![res](https://user-images.githubusercontent.com/9817522/40758908-3873e442-6498-11e8-965f-6d88c1120cea.PNG)

I think there is bot detection. Original xNet won't pass this test.
But Leaf using native CookieStorage with crossdomain support and expire control.
