### ISSUE TITLE
Cookies with dot error

### ISSUE THREAD

**Issue by guzlewski** [csharp-leaf/Leaf.xNet#31]
Hello, there is again issue with cookies from domains with dot. Last working version 5.1.55.
Example of domain throwing error: Domain=.retail-mobile-prod

**Comment by grandsilence** [comment]
Can you provide an example of URL for tests?

**Comment by guzlewski** [comment]
https://app.petro-canada.ca/en/forgot-password.aspx

**Comment by grandsilence** [comment]
Fixed in v5.1.62 . Can I close the issue?

**Comment by guzlewski** [comment]
I dont know why but now I have this error 
`Leaf.xNet.HttpException: The error on the client side. Status code: 404
   w Leaf.xNet.HttpRequest.CheckStatusCode(HttpStatusCode statusCode)
   w Leaf.xNet.HttpRequest.Request(HttpMethod method, Uri address, HttpContent content)
   w Leaf.xNet.HttpRequest.Raw(HttpMethod method, Uri address, HttpContent content)
   w Geniush.PetroCanada.Tokens(ProxyClient proxy)`
On version 5.1.55 working, I use proxy.

**Comment by grandsilence** [comment]
I’ve got same status code and “Rejected” in the body of response. But after connection to my Germany VPN the issue has gone.

**Comment by guzlewski** [comment]
I tried without proxy and that was ok, working. With proxy this error, the same proxies work with old version. I can send you these proxies for tests.

**Comment by grandsilence** [comment]
Please try to disable absolute path for your proxy server:
```
httpRequest.Proxy.AbsoluteUriInStartingLine = false;
```
This will use relative URL in starting line header for your proxy server.
It will set the same behaviour like **v5.1.55**.

**Comment by guzlewski** [comment]
Now its working good, thanks :+1:
