### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by ThunderCls** [csharp-leaf/Leaf.xNet#35]
I'm having some issues when dealing with custom headers for a request. So far I have something like:

```csharp
httpRequest.KeepTemporaryHeadersOnRedirect = true;
httpRequest.EnableMiddleHeaders = true;

httpRequest.AddHeader("Custom-Header1", "CustomValue1");
httpRequest.AddHeader("Custom-Header2", "CustomValue2");
httpRequest.AddHeader("Custom-Header3", "CustomValue3");

while(true)
    var httpResponse = httpRequest.Post(myUrl, postData, "application/x-www-form-urlencoded; charset=UTF-8");
```

The issue is that only the first POST request of the loop is using the custom headers set at the beginning of the code. In order for the subsequent requests to include those custom headers as well, I need to explicitly state so every time before the request is made. I've set the KeepTemporaryHeadersOnRedirect and EnableMiddleHeaders but they don't seem to make a difference at all for my problem.
My question is how can I make those temporary headers like permanent without having to set them every single time before every request

**Comment by grandsilence** [comment]
You are using all methods and properties incorrectly.
`EnableMiddleHeaders` required when you have redirect/s and need to get response headers for redirected requests (not only the last one response headers).

`KeepTemporaryHeadersOnRedirect` working only for redirects. The second one call of `httpRequest.Post` and others aren't redirect... (thats a new `Post` request).
Method `AddHeader` adds a header only for the next request. In other cases, the indexer is used:
```csharp
httpRequest["Custom-Header1"] = "CustomValue1";
```

**Comment by ThunderCls** [comment]
Cool, thanks! and keep up the good work with this project
