### ISSUE TITLE
request.GetThroughCloudflare(url) overwrites headers

### ISSUE THREAD

**Issue by AsianPotato** [csharp-leaf/Leaf.xNet#40]
Im setting accept: application/json header and it gets overridden, it doesn't get overridden when using .Get() though.

**Comment by grandsilence** [comment]
> Cloudflare bypass not maintained in **public Leaf.xNet** anymore.  
  Only private Leaf.xNet with support.  
  Telegram: [@kelog](https://t.me/kelog)
