### ISSUE TITLE
Как сохранить куки на следующий запрос?

### ISSUE THREAD

**Issue by madroot** [csharp-leaf/Leaf.xNet#41]
В примерах показан такой код:
```
using (var request = new HttpRequest()) {
    // Do something
}
// Or
HttpRequest request = null;
try {
    request = new HttpRequest();
    // Do something 
}
catch (HttpException ex) {
    // Http error handling
    // You can use ex.Status or ex.HttpStatusCode for more details.
}
catch (Exception ex) {
	// Unhandled exceptions
}
finally {
    // Cleanup in the end if initialized
    request?.Dispose();
}
```

Но в таком случае куки на каждый запрос будут чистые куки, т.к request  инициализируется по новой, а если эт строчку убрать, то будет утечка памяти? 
Как правильно делать несколько запросов что бы сохранялись куки?

**Comment by grandsilence** [comment]
Попробуйте использовать общий экземпляр `CookieStorage` для `HttpRequest` через свойство `HttpRequest.Cookies`.
