### ISSUE TITLE
MessageBodyLoaded Weird Issue

### ISSUE THREAD

**Issue by ThunderCls** [csharp-leaf/Leaf.xNet#42]
I don't know if I'm not using this how it's supposed to be used or this is just playing tricks with my mind, but I'm getting a pretty weird bug with the MessageBodyLoaded property of HttpResponse objects. I got a simple code something like this:

```csharp
HttpRequest httpRequest = new HttpRequest();
HttpResponse httpResponse = null;

try
{
    httpResponse = httpRequest.Get("http://www.google.com");
}
catch { }

bool? bodyLoaded = httpResponse?.MessageBodyLoaded; // This line is giving weird results
```
Every time I run this code ***bodyLoaded*** becomes false, even when ***MessageBodyLoaded*** is always true. Now, the weird behavior occurs by that only when stepping over that line on the debugger is that ***bodyLoaded*** becomes true. What am I missing here? I'm using the latest version (5.1.76) of Leaf.xNet from nuget.

**Comment by grandsilence** [comment]
By default MessageBody won't be loaded when you called request method.
```csharp
    httpResponse = httpRequest.Get("http://www.google.com");
    httpResponse.None(); // load body and do nothing with it

**Comment by ThunderCls** [comment]
Ok what I actually was trying to avoid was the Leaf.xNet.HttpException when calling .ToString() method other than by using try/catch, I thought MessageBodyLoaded would help with the "Could not receive the message body of the response HTTP-server" exception I've been getting sometimes...by only checking on that attribute before accessing the .ToString() method

**Comment by grandsilence** [comment]
Can you try another xNet from issue #44 ? Check for this error: "Could not receive the message body of the response HTTP-server". If it's not, please inform me here.

**Comment by swooshXE** [comment]
I'm still getting "Could not receive the message body of the response HTTP-server" when some HTTPs proxies are used, even with "AbsoluteUriInStartingLine = false;". Using the default HttpClient by Microsoft with the same proxie, works just fine.
