### ISSUE TITLE
Support all weird types of proxies like xNet-Ameliorated did

### ISSUE THREAD

**Issue by grandsilence** [csharp-leaf/Leaf.xNet#44]
Should test on luminati proxies.

[xNet-Ameliorated.zip](https://github.com/csharp-leaf/Leaf.xNet/files/3327252/xNet-Ameliorated.zip)

**Comment by x-serious** [comment]
make it support luminate proxies , it's weird long text , like a hostname and user:pass in it + port

**Comment by grandsilence** [comment]
HINT: Sometimes HTTPS proxy require relative address instead of absolute.
This behavior can be changed:
```csharp
http.Proxy.AbsoluteUriInStartingLine = false;
```
