### ISSUE TITLE
Convert CookieStorage to/from bytes

### ISSUE THREAD

**Issue by moabtools** [csharp-leaf/Leaf.xNet#45]
I don't really familiar with github, so I will propose here. In some cases very useful function is conversion CookieStorage to/from bytes array. The additional code in CookieStorage.cs looks like:
```
/// <summary>
/// Сохраняет куки в массив байт.
/// </summary>
// ReSharper disable once UnusedMember.Global
public byte[] ToBytes()
{
    byte[] r;

    using (var ms = new MemoryStream())
    {
        Bf.Serialize(ms, this);
        r = ms.ToArray();
    }

    return r;
}

/// <summary>
/// Загружает <see cref="CookieStorage"/> из массива байт.
/// </summary>
/// <param name="bytes">Массив байт</param>
/// <returns>Вернет <see cref="CookieStorage"/>, который задается в свойстве <see cref="HttpRequest"/> Cookies.</returns>
// ReSharper disable once UnusedMember.Global
public static CookieStorage FromBytes(byte[] bytes)
{
    using(var ms = new MemoryStream(bytes))
        return (CookieStorage)Bf.Deserialize(ms);
}
```

Will appreciate if you will add this to the next release.

**Comment by ahvahsky2008** [comment]
And cookiecontainer - cookiecollection pls!!!!)))))))))) Очень ннадо

**Comment by grandsilence** [comment]
> And cookiecontainer - cookiecollection pls!!!!)))))))))) Очень ннадо
Для чего? Там же есть метод получения по URL, который вернет CookieCollection.

**Comment by ahvahsky2008** [comment]
@grandsilence  иногда бывает необходимо

**Comment by grandsilence** [comment]
@ahvahsky2008 можете сделать pull request, рассмотрю заявку. Реализовать не планирую.

**Comment by grandsilence** [comment]
Released in v5.2.3
