### ISSUE TITLE
Can't use http proxy

### ISSUE THREAD

**Issue by khang0001** [csharp-leaf/Leaf.xNet#5]
When I use http proxy with Leaf.Net it say 400 error
here my code

> using  (var request = new Leaf.xNet.HttpRequest())
>    {
 >       request.Proxy = new Leaf.xNet.HttpProxyClient("1.1.1.1", 3128);
 >       string html = request.Get("http://api.ipify.org/").ToString();
  >  }

But I use same http proxy with xNet lib. It by pass very good
Here is my code with xNet

>using (var request = new xNet.HttpRequest())
>            {
 >               request.Proxy = xNet.HttpProxyClient.Parse("1.1.1.1:3128");
  >              string html = request.Get("http://api.ipify.org/").ToString();
    >        }

How can I fix to make Leaf.xNet use http proxy success?

**Comment by grandsilence** [comment]
Don't use `new Leaf.xNet.HttpProxyClient("1.1.1.1", 3128);`
It's not working in original xNet too. You should always use `Parse` method for proxies.

Try like this
```csharp
using (var request = new Leaf.xNet.HttpRequest())
{
    request.Proxy = Leaf.xNet.HttpProxyClient.Parse("1.1.1.1:3128");
    string html = request.Get("http://api.ipify.org/").ToString();
}
```

**Comment by khang0001** [comment]
When I use
>using (var request = new Leaf.xNet.HttpRequest())
>{
  >  request.Proxy = Leaf.xNet.HttpProxyClient.Parse("1.1.1.1:3128");
>    string html = request.Get("http://api.ipify.org/").ToString();
> }

It have error "The error on the client side. Status code: 400" . How can I fix it?

**Comment by grandsilence** [comment]
Check that your proxy is valid (Proxifier for example). Or send me your proxy to Telegram [@kelog](https://telegram.me/kelog).

**Comment by khang0001** [comment]
Already pm you via telegram info my proxy. Please check my inbox. Thanks

**Comment by grandsilence** [comment]
![screenshot_1](https://user-images.githubusercontent.com/9817522/43667533-fe94075e-9780-11e8-9af0-ade9191734cf.png)

**Comment by grandsilence** [comment]
I don't know what is it. But `Get("http://whoer.net")` sometimes throws `IOExcepton` or `HttpException 400 status code`.

You can use native HttpClient:
```csharp
            var handler = new HttpClientHandler();
            var httpClient = new HttpClient(handler);
            handler.Proxy = new WebProxy(new Uri("http://174.129.174.134:10000"));

            var task = httpClient.GetStringAsync("http://whoer.net");
            task.ConfigureAwait(false);

            string result = task.Result;
```

**Comment by grandsilence** [comment]
Fixed

**Comment by igorbiliba** [comment]
> Fixed

No sir :(
Im have this problem again. 
This problem show only after some steps on site.
