### ISSUE TITLE
response.ToString() error without proxy

### ISSUE THREAD

**Issue by biom3tric** [csharp-leaf/Leaf.xNet#51]
Hello, i got this weird error. I'm trying to load a large webpage (The Content-Length is around 50 000) and when i want to get the source code using `response.ToString()`, this throw an error:
![](http://0x0.st/zWuy.png)

The weird thing of this issue, is when i use a reverse proxy like Fiddler, it loads directly, but without proxies it won't load.

Thank you in advance.

**Comment by grandsilence** [comment]
Send me URL and your proxy for tests. Telegram: https://t.me/kelog

**Comment by biom3tric** [comment]
Fixed using NET Core 2.2 instead of 3.0 preview.
