### ISSUE TITLE
CF Bypass not working on some sites

### ISSUE THREAD

**Issue by jojodat** [csharp-leaf/Leaf.xNet#53]
Hi,
i'm getting a "Specified argument was out of the range of valid values" 
On some sites.

for example on
https://uam.hitmehard.fun/HIT

or some other sites listed on Tested sites on this project:
https://github.com/RyuzakiH/CloudflareSolverRe

**Comment by grandsilence** [comment]
@jojodat https://github.com/RyuzakiH/CloudflareSolverRe has the same issue?

**Comment by meinname** [comment]
No, it's working on CloudflaresolverRe.
Maybe you can copy their js solving code ;)

**Comment by grandsilence** [comment]
Okay. I will try to find time to fix this problem.

**Comment by meinname** [comment]
BTW: I noticed, http://lionroyalcpk.club:2082/ from your CloudflareDemo Example has also the problem. Seems CF is rolling it slowly but more and more sites get it.

**Comment by meinname** [comment]
FYI: A Few Days ago Cloudflare made a change which now also broke the remaining sites - So currently Leaf.xNet can't bypass no Cloudflare Challenges anymore.
 "s" seems to have been replaced with "r"

**Comment by eastsida** [comment]
Yeah, i am getting the same issue
"Leaf.xNet.Services.Cloudflare.CloudflareException" in Leaf.xNet.dll
 Value of "s" not found

**Comment by grandsilence** [comment]
Cloudflare bypass not maintained in **public Leaf.xNet** anymore.
Only private Leaf.xNet with support.
