### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by SpellV2** [csharp-leaf/Leaf.xNet#59]
Hello im coding a Checker but needs cookie capturing :/ how can i capture cookies ? and writing post data ?

**Comment by AnErrupTion** [comment]
@SpellV2 for the cookies, you can just get each cookies in a foreach loop and get the name or value of it.
For the post data, you can directly include it while doing the request (using req.Get or req.Post).

**Comment by SpellV2** [comment]
@AnErrupTion You can show me an example ?

**Comment by AnErrupTion** [comment]
for the cookies :
`foreach (var cookie in req.Cookies)
{
    if (cookie.Key == "foo" || cookie.Value == "bar")
    {
        // Do something useful here
    }`

for the post data :
`string response = req.Post("https://www.example.com/login", new BytesContent(Encoding.UTF8.GetBytes("email=foo@gmail.com&password=bar123"))).ToString();`
