### ISSUE TITLE
Translate code comments to english?

### ISSUE THREAD

**Issue by Zeokat** [csharp-leaf/Leaf.xNet#60]
Seems that all the info is under english language, but when you browse code, comments are in russian.

Translate them will be helpfull for developers and potential users.

**Comment by AnErrupTion** [comment]
@Zeokat actually, this will be time consuming for nothing.
If the exceptions are already in english, then there is no need to do the same for the direct code commands. And really, they are useless because most of them will just say what the current class does.
So unless you really don't know how to code, then these comments are useless.

**Comment by Zeokat** [comment]
> 
> 
> @Zeokat actually, this will be time consuming for nothing.
> If the exceptions are already in english, then there is no need to do the same for the direct code commands. And really, they are useless because most of them will just say what the current class does.
> So unless you really don't know how to code, then these comments are useless.

Honestly, know what current class do is a huge help for some developers. But i understand that is time consuming, but i don't see that as wasting time. Anyway thanks for your reply.

**Comment by grandsilence** [comment]
> @Zeokat actually, this will be time consuming for nothing.
> If the exceptions are already in english, then there is no need to do the same for the direct code commands. And really, they are useless because most of them will just say what the current class does.
> So unless you really don't know how to code, then these comments are useless.
I totally agree with you. I don't see any point in wasting time on this. It is better to invest this time in fixing bugs.
