### ISSUE TITLE
Browser Emulation Support

### ISSUE THREAD

**Issue by ThunderCls** [csharp-leaf/Leaf.xNet#62]
Any future plans on implementing browser/js emulation? something like an HtmlWeb.LoadFromBrowser from HtmlAgilityPack or any other headless browser integration?

**Comment by biom3tric** [comment]
You should look at Selenium (slow but works with C#) or better is Puppeteer (faster, but works with JS)

**Comment by grandsilence** [comment]
It's HTTP only library. @biom3tric gave good advice, listen to him.
