### ISSUE TITLE
Set cookie on post give error

### ISSUE THREAD

**Issue by s00ny5** [csharp-leaf/Leaf.xNet#63]
Ok so I used
`var cookie = new Cookie(string name, string value, string domain, string path);
request.Cookies.Set(cookie);`

where Cookie is System.Net.Cookie

This give an error:
` Object reference not set to an instance of an object.`

Any help in this?

**Comment by grandsilence** [comment]
```
// After init httpRequest 
httpRequest.Cookies = new CookieStorage()
```
Before request
