### ISSUE TITLE
Prompt exception in case of high concurrency

### ISSUE THREAD

**Issue by whgfu** [csharp-leaf/Leaf.xNet#64]
There is no problem with concurrency in 10 threads, but when I test 40 threads, there will be errors
Leaf.xNet.HttpException
  HResult=0x80131500
  Message=**It turned out wait for a connection to the HTTP-server** 'mbd.baidu.com'.
  Source=Leaf.xNet
  StackTrace:
   在 Leaf.xNet.HttpRequest.CreateTcpConnection(String host, Int32 port)
   在 Leaf.xNet.HttpRequest.CreateConnection(Uri address)
   在 Leaf.xNet.HttpRequest.TryCreateConnectionOrUseExisting(Uri address, Uri previousAddress)
   在 Leaf.xNet.HttpRequest.Request(HttpMethod method, Uri address, HttpContent content)
   在 Leaf.xNet.HttpRequest.Raw(HttpMethod method, Uri address, HttpContent content)
   在 Leaf.xNet.HttpRequest.Raw(HttpMethod method, String address, HttpContent content)
   在 Leaf.xNet.HttpRequest.Get(String address, RequestParams urlParams)

**Comment by abhay991** [comment]
Do you use proxy? I think host is not replying your connect request.

**Comment by developervariety** [comment]
This is currently happening to me with `roblox-api.arkoselabs.com`

Once I go above `15` threads an exception is thrown with this exact exception!

**Comment by grandsilence** [comment]
The issue is closed due to inactivity.
