### ISSUE TITLE
Can not request post with datapost json

### ISSUE THREAD

**Issue by meomup** [csharp-leaf/Leaf.xNet#66]
Hi developer !
I tried a lot of time request post with datapost is json data, with data-json easy, leafxnet post success, but with data-json need encodehtml, the sever response is worng body datapost.
Could you please guide me how to post with datapost is string json ?
here page you can test : 
https://www.realtor.com/realestateandhomes-detail/15-Broad-St-Apt-904_New-York_NY_10005_M49452-80308 -> click email agent to get post request.
how could i request post it right ?

**Comment by grandsilence** [comment]
```csharp
var response = httpRequest.Post("https://google.com/", "{yourJson:true}", "application/json");
string responseString = response.ToString();
```

**Comment by meomup** [comment]
@grandsilence thanks you. but now i see header again.. it is not json data, it is : application/x-www-form-urlencoded; charset=UTF-8 .
normaly, i only post with data decode, leafxnet auto encode, but seem leafxnet wrong encode with data of site realtor.com. or i manual encode my data...
i see "[" -> encode -> %5B, "]" -> encode -> %5D ... do you know what's name of encode ?

**Comment by abhay991** [comment]
That's UrlEncode. You can use UrlEncode Method of WebUtility class from System.Net.

Also this is basic example for that site.

```
using (var req = new HttpRequest())
{
    var reqParams = new RequestParams();
    reqParams["id"] = "blaBla";
    reqParams["formdata"] = "[{\"type\":\"tel\",\"name\":\"leads_form_data[phone]\",\"value\":\"123456789\"}]"; //this is your json data
         
    req.Post("https://www.realtor.com/post", reqParams);
}
```

**Comment by meomup** [comment]
> 
> 
> That's UrlEncode. You can use UrlEncode Method of WebUtility class from System.Net.
> 
> Also this is basic example for that site.
> 
> ```
> using (var req = new HttpRequest())
> {
>     var reqParams = new RequestParams();
>     reqParams["id"] = "blaBla";
>     reqParams["formdata"] = "[{\"type\":\"tel\",\"name\":\"leads_form_data[phone]\",\"value\":\"123456789\"}]"; //this is your json data
>          
>     req.Post("https://www.realtor.com/post", reqParams);
> }
> ```

Thanks you bro... extract is using RequestParams with data json 👍 👍 👍
