### ISSUE TITLE
How to parse through Dns.GetHostEntry.AddressList IPs?

### ISSUE THREAD

**Issue by moabtools** [csharp-leaf/Leaf.xNet#67]
I have some IP addresses on my server (10 addresses):

```
var t = Dns.GetHostEntry(Dns.GetHostName()).AddressList.Where(o => o.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
```

How can I parse through all those IP addresses at the same time using Leaf.xNet?

**Comment by grandsilence** [comment]
I'm sorry, but there's no such opportunity right now, and I don't plan on implementing it. You can create pull request for the feature.
