### ISSUE TITLE
Проблема с cookies

### ISSUE THREAD

**Issue by Ubahmed** [csharp-leaf/Leaf.xNet#7]
Здравствуйте.
Делаю Get запрос к одному сайту и получаю такую ошибку:

![1](https://user-images.githubusercontent.com/42672530/44582169-5b6d4700-a7a9-11e8-8859-b3f81d3cfb4a.PNG)

Я так понимаю ошибка через то что сайт выдает какой то левый формат кукисов.
Пробую еще через свойство DontTrackCookies отключить обработку кукисов так как они мне не нужны, но тоже получаю ошибку:

![2](https://user-images.githubusercontent.com/42672530/44582177-62945500-a7a9-11e8-86db-b85bbcee2958.PNG)

Такая проблема только с этим сайтом, с другими все норм.

**Comment by Ubahmed** [comment]
Сам сайт: https://tinybuildgames.us7.list-manage.com/subscribe?u=7c5ba06b8b6710be2a32d1afc&id=5211b170b7

**Comment by grandsilence** [comment]
Исправил поведение `DontTrackCookies`, но теперь и парсинг куки не выдаст ошибку - написал свой разбор `Cookie`. 

Microsoft поленились реализовать нормальный парсинг параметра `rawCookie` в `Cookie.Add` исключение в их коде.

**Comment by Ubahmed** [comment]
Спасибо большое за быстрый фикс.

**Comment by grandsilence** [comment]
Пожалуйста
