### ISSUE TITLE
Asynchronous requests

### ISSUE THREAD

**Issue by Acheiro** [csharp-leaf/Leaf.xNet#72]
I'd like to suggest taking under consideration addition of asynchronous versions of the HTTP request methods. It would be lovely to combine this lib with native .NET ThreadPool.

**Comment by grandsilence** [comment]
Unfortunately, in order to implement this, we need to completely rewrite the library. If you have enough free time and experience, you can try to implement it. The repository is open for pull request.

**Comment by Acheiro** [comment]
Hmm I might give it a shot after I'm finished with my current project. I don't really have the experience necessary for the sockets but I guess it is just time to finally gain it ¯\_(ツ)_/¯
