### ISSUE TITLE
Problem with overload

### ISSUE THREAD

**Issue by Nanilanko** [csharp-leaf/Leaf.xNet#73]
Hello I'm trying to make one checker and when I try to make

HttpRequest.Get it says that: Error	2	No overload for method 'Get' takes 7 arguments	

That's the request what I would like to make :

httpRequest.Get("https://www.blablabla.com/r/ajax/SignIn.jsp?deviceType=blablabla&email=",user[0],"&idfa=f09db2c7-4bbd-4d46-a62d-085978c717aa&isCheckout=true&appVersion=6.9.0&pw=",user[1],"&iphoneId=android&userEmail=",user[0],"".ToString());

Did anyone know a solution?

**Comment by grandsilence** [comment]
You have incorrect syntax. Learn C#  harder.
```csharp
httpRequest.Get("https://www.blablabla.com/r/ajax/SignIn.jsp?deviceType=blablabla&email=" + user[0] + "&idfa=f09db2c7-4bbd-4d46-a62d-085978c717aa&isCheckout=true&appVersion=6.9.0&pw=" + user[1] + "&iphoneId=android&userEmail=" + user[0]).ToString());
```
