### ISSUE TITLE
Unable to connect to server after fixed amount of requests

### ISSUE THREAD

**Issue by SuperLanceur** [csharp-leaf/Leaf.xNet#75]
I'm trying to connect to a server multiple times. Multi-threading allows me to reach 16k connections but after 16164-16181 (always in that range) connections they won't open anymore. "Unable to reach server x". The server I'm trying to connect to is on localhost and hardware isn't the issue. (Tested using entreprise-grade hardware)

**Comment by abhay991** [comment]
Are you sure you are disposing the request properly after using it? Problem occurs when your proxy provider allows you limited number of streams to be open and then when you reach that number it will throw error. Please provide more details on this along with exception log.

**Comment by TnEmpire** [comment]
> Are you sure you are disposing the request properly after using it? Problem occurs when your proxy provider allows you limited number of streams to be open and then when you reach that number it will throw error. Please provide more details on this along with exception log.

if u could show us how to dispose request  .

**Comment by abhay991** [comment]
> > Are you sure you are disposing the request properly after using it? Problem occurs when your proxy provider allows you limited number of streams to be open and then when you reach that number it will throw error. Please provide more details on this along with exception log.
> 
> if u could show us how to dispose request .

1. Using Statement
```
using(var r = new HttpRequest())
{
  //call get/post or other methods
}
```
2. Calling Dispose function directly.
```
var r = new HttpRequest();
r.Dispose();
```

**Comment by TnEmpire** [comment]
> > > Are you sure you are disposing the request properly after using it? Problem occurs when your proxy provider allows you limited number of streams to be open and then when you reach that number it will throw error. Please provide more details on this along with exception log.
> > 
> > 
> > if u could show us how to dispose request .
> 
> 1. Using Statement
> 
> ```
> using(var r = new HttpRequest())
> {
>   //call get/post or other methods
> }
> ```
> 
> 1. Calling Dispose function directly.
> 
> ```
> var r = new HttpRequest();
> r.Dispose();
> ```

thank you this solved my issue. if you could explain why i would appreciate it

**Comment by grandsilence** [comment]
The issue is closed due to inactivity.
