### ISSUE TITLE
SOCKS5 Parse

### ISSUE THREAD

**Issue by CarterTO** [csharp-leaf/Leaf.xNet#76]
Sup, Ive noticed I can not parse SOCKS5 Like:

socks5://WYqCwhfIq70j:xSJhPwvyoQ@nyc-a44.domain.com:1080

anyone have any suggestions? 

`System.FormatException: The port can not be less than 1 or greater than 65535. ---> System.FormatException: Input string was not in a correct format. at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) at Leaf.xNet.ProxyClient.Parse(ProxyType proxyType, String proxyAddress) --- End of inner exception stack trace --- at Leaf.xNet.ProxyClient.Parse(ProxyType proxyType, String proxyAddress) at Leaf.xNet.Socks5ProxyClient.Parse(String proxyAddress) at CheckerBase.CheckerHelper.Check() in C:\Users\decla\Desktop\Developing\Sources\In Development\UFC Checker\CheckerBaseSource\CheckerHelper.cs:line 143`

**Comment by CarterTO** [comment]
`System.FormatException: The port can not be less than 1 or greater than 65535. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Leaf.xNet.ProxyClient.Parse(ProxyType proxyType, String proxyAddress)
   --- End of inner exception stack trace ---
   at Leaf.xNet.ProxyClient.Parse(ProxyType proxyType, String proxyAddress)
   at Leaf.xNet.Socks5ProxyClient.Parse(String proxyAddress)
   at CheckerBase.CheckerHelper.Check() in C:\Users\decla\Desktop\Developing\Sources\In Development\UFC Checker\CheckerBaseSource\CheckerHelper.cs:line 143`

**Comment by grandsilence** [comment]
Create instance of socks proxy via `new` and set required properties.

**Comment by abhay991** [comment]
var rawProxy = "socks5://WYqCwhfIq70j:xSJhPwvyoQ@nyc-a44.domain.com:1080";
            var _pdata = rawProxy.Substring(9);
            var proxydata = _pdata.Split('@');
            var userdata = proxydata[0].Split(':');
            var proxy = proxydata[1].Split(':');
            var host = proxy[0];
            var port = int.Parse(proxy[1]);
            var id = userdata[0];
            var pass = userdata[1];
            using (var r = new Leaf.xNet.HttpRequest())
            {
                r.Proxy = new Leaf.xNet.Socks5ProxyClient(host, port, id, pass);
            }

**Comment by dragontang123** [comment]
@abhay991 didn't work but i solved it
