### ISSUE TITLE
Setting new proxy instance issue.

### ISSUE THREAD

**Issue by Teh1337Online** [csharp-leaf/Leaf.xNet#80]
Basically im trying to auth to proxy(host:port:user:pass), it works perfectly fine on a couple of threads., but if i go above 5 I fail to connect. 

ERROR 1:
`Leaf.xNet.HttpException: Unable to connect to the HTTP-server 'creator.wg.spotify.com'. ---> Leaf.xNet.ProxyException: Received invalid status code 'ProxyAuthenticationRequired' on 'gate.dc.smartproxy.com:20000' proxy`.

ERROR 2:
`Leaf.xNet.HttpException: It turned out wait for a connection to the HTTP-server 'creator.wg.spotify.com'.
`

CODE:

```
string[] rawProxy = Program.getProxy().Split(':');
var host = rawProxy[0];
int port = Int32.Parse(rawProxy[1]);
var user = rawProxy[2];
var pass = rawProxy[3];

req.Proxy = new Leaf.xNet.HttpProxyClient(host, port, user, pass);
```

**Comment by abhay991** [comment]
hi, ask your proxy provider if they have limited number of streams allowed per proxy.

**Comment by Teh1337Online** [comment]
> hi, ask your proxy provider if they have limited number of streams allowed per proxy.

Hi, Yea i got that part sorted now, its just 

this: 

Received invalid status code 'ProxyAuthenticationRequired'

**Comment by abhay991** [comment]
It should work if you are passing right details, also check if you are disposing requests properly after their use cause if your connection remains open it will be marked as active stream by proxy server which will mean your number of streams will get limited as you go. Post complete code or let's just wait for @grandsilence

**Comment by Teh1337Online** [comment]
Solved. Thanks for the help
