### ISSUE TITLE
Auto Redirect Max Concurrent reached. 

### ISSUE THREAD

**Issue by Teh1337Online** [csharp-leaf/Leaf.xNet#81]
Basically, a website has multiple redirects for example:

**INITIAL REQUEST:**
POST: www.website.com/login/ [302]

**REDIRECTS:**
GET[1]: www.website.com/cardholder [Status: 301]
GET[2]: www.website.com/cardholder/ [Status: 302]
GET[3]: www.website.com/cardholder/en/ [Status: 302]
GET[4]: www.website.com/cardholder/en/ [Status: 200]

___

GET[1]: The first redirect contains a body of "301 Moved Permanently"
GET[2]: The second redirect contains an EMPTY body
GET[3]: The third redirect contains a body of "Request sent"
GET[4]: The fourth redirect contains the body of the information I need to capture

____

I set AllowAutoRedirect to True, and set a max auto redirect to 4, but I get an exception of Max Concurrent's. Anyone know a work around? I have tried manually redirecting these requests but it just sends me to : GET[1] and GET[3]

All headers during the redirects are the EXACT Same. 

____
**ERROR:**

> Leaf.xNet.HttpException: Have exceeded the maximum number of consecutive redirects.

Thanks if you can help.

**Comment by grandsilence** [comment]
I'll check I have access to my PC.

**Comment by Teh1337Online** [comment]
> I'll check I have access to my PC.

I did find a way around it by setting the initial post request to redirect, I just found a slight difference in code when a login failed. Took a while to find as it was almost identical. Would be great if I could set this to false then follow the first manual redirect then allow auto redirect on there.
