### ISSUE TITLE
Problem with connection.

### ISSUE THREAD

**Issue by mert1291** [csharp-leaf/Leaf.xNet#82]
"Unable to establish SSL-connection with HTTP-server."I get this error many times

**Comment by grandsilence** [comment]
OS, Resource URL, Platform and version of platform (.NET Core / Framework). Proxy used?

**Comment by mert1291** [comment]
Windows 10 url netflix.com .net core proxy using  leaf xnet :v4.0.30319

**Comment by MeGaZip** [comment]
I have the same errors.
As with proxies as without proxies.
I tried this one 
request.SslProtocols = 
	SslProtocols.Ssl2 |
	SslProtocols.Ssl3 |
	SslProtocols.Tls |
	SslProtocols.Tls11 |
	SslProtocols.Tls12 |
	SslProtocols.Tls13;
it did not help.

**Comment by abhay991** [comment]
> Windows 10 url netflix.com .net core proxy using leaf xnet :v4.0.30319

Netflix has TLS 1.2 enabled, everything else is disabled so if your proxy are not public and have ssl/tls support then it should work. Are you using public proxies?

**Comment by mert1291** [comment]
ı using private ipv6 proxies

**Comment by grandsilence** [comment]
> ı using private ipv6 proxies

ipv6 is not supported

**Comment by mert1291** [comment]
ipv4 to  ipv6 proxy using

**Comment by grandsilence** [comment]
@mert1291 
> ipv4 to ipv6 proxy using

is target website supports ipv6?

**Comment by mert1291** [comment]
yeah site support ipv6

**Comment by abhay991** [comment]
Just checked Netflix with ipv6 socks5 proxy and it's working perfectly fine for me atleast.

**Comment by mert1291** [comment]
ok
