### ISSUE TITLE
URI Invalid - Unable to parse name host

### ISSUE THREAD

**Issue by Velka-DEV** [csharp-leaf/Leaf.xNet#87]
Hi sir,

i'am just trying to set cookies in my project. But i'am facing exception when i set them.

`
Cookie cookie_test = new Cookie("TEST", "test", "google.com", "/");

request.Cookies.Set(cookie_test);
`

Exception:  'System.UriFormatException' in System.dll
Invalid URI : Unable to parse name host

Thanks for your work

**Comment by abhay991** [comment]
Add method with 4 parameter has domain name at last.

**Name**, **Value**, **Path**, **Domain**

`new Cookie("TEST", "test", "/", "google.com")`

**Comment by Velka-DEV** [comment]
Thanks i was baited by method parameters names

`
public void Set(string name, string value, string **domain**, string path = "/")
{
    var cookie = new Cookie(name, value, path, **domain**);
    Set(cookie);
}
`
