### ISSUE TITLE
Unable to handle JSON Rest API response

### ISSUE THREAD

**Issue by Velka-DEV** [csharp-leaf/Leaf.xNet#88]
> Leaf.xNet.HttpException: Failed to receive the response from the HTTP-server 'www.google.com'. ---> System.IO.IOException: Unable to read data from the transport connection: An attempt to connect to a car failed the connected party did not respond properly after a certain time or an established connection to a car failed the connection host n did not respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not respond properly beyond a certain time, or an established connection failed because the connection host did not respond
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à Leaf.xNet.HttpResponse.ReceiverHelper.ReadLine()
   à Leaf.xNet.HttpResponse.ReceiveStartingLine()
   à Leaf.xNet.HttpResponse.LoadResponse(HttpMethod method, Boolean trackMiddleHeaders)
   --- Fin de la trace de la pile d'exception interne ---
   à Leaf.xNet.HttpResponse.LoadResponse(HttpMethod method, Boolean trackMiddleHeaders)
   à Leaf.xNet.HttpRequest.ReceiveResponseHeaders(HttpMethod method)
   à Leaf.xNet.HttpRequest.Request(HttpMethod method, Uri address, HttpContent content)
   à Leaf.xNet.HttpRequest.Raw(HttpMethod method, Uri address, HttpContent content)
   à Leaf.xNet.HttpRequest.Raw(HttpMethod method, String address, HttpContent content)
   à Leaf.xNet.HttpRequest.Post(String address, Byte[] bytes, String contentType)

With same headers, cookie, method, ECT in python requests i get JSON Rest Response but with Leaf.xNet is unable to handle the response

Header (+ basics like User-Agent ect..)
request.AddHeader("Content-Type", "application/x-protobuffer");
request.AddHeader("Connection", "keep-alive");

var resp = request.Post("API URL", bytes, "application/x-protobuffer");

**Comment by Velka-DEV** [comment]
I have tried with an different API with normal content type and same result.

Leaf.xNet is not designed to handle JSON response ?

**Comment by grandsilence** [comment]
Protobuf is binary protocol and not supported by Leaf.xNet.
