### ISSUE TITLE
Leaf.xnet 5.2.10 not returning post data on certain sites, worked before on 5.2.8

### ISSUE THREAD

**Issue by dragontang123** [csharp-leaf/Leaf.xNet#95]
I had just updated my leaf.xnet to the latest version and found that it has some issue with the post request, as it's not returning anything even though there is a response form the server. Issue doesnt occur in 5.2.8

**Comment by grandsilence** [comment]
URL for example?

**Comment by dragontang123** [comment]
I can't replicate this anymore lost the link. Pls close it

**Comment by grandsilence** [comment]
OK. Make a new issue if the problem repeats and provide the URL there.
