### ISSUE TITLE
Auth Proxies

### ISSUE THREAD

**Issue by dragontang123** [csharp-leaf/Leaf.xNet#96]
Is there anyway in leaf.xnet to use ip:port:user:pass proxies? I tried to use new HttpProxyClient(host,ip,user,pass) to accomplish that but it didnt work

**Comment by abhay991** [comment]
https://github.com/csharp-leaf/Leaf.xNet/issues/76

Please check this.

**Comment by dragontang123** [comment]
Solved

var proxy= HttpProxyClient.Parse("ip:port");
proxy.Username = ""; proxy.Password = "";
