### ISSUE TITLE
Error with 404

### ISSUE THREAD

**Issue by HideakiAtsuyo** [csharp-leaf/Leaf.xNet#98]
![leaf](https://user-images.githubusercontent.com/53636771/88484744-2a878500-cf71-11ea-89da-916bc1101578.png)

**Comment by grandsilence** [comment]
So? It's correct status code: Not found.
Use ```
httpRequest.IgnoreProtocolErrors = true;
```
To disable exceptions or handle it try-catch block.

**Comment by HideakiAtsuyo** [comment]
Oh nice thanks!
